version: '3'

services:
  app:
    image: codesort-php7-apache
    container_name: codesort-apache
    build: docker
    ports:
      - "8075:80"
      - "9099:9000"
    depends_on:
      - mysql
    volumes:
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./rector.php:/app/rector.php
      - ./public:/app/public
      - ./docker/app/codes-config.php:/app/public/codesort2/codes-config.php:ro
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - mysql
    networks:
      - internal

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: codesort_docker
      MYSQL_USER: codesort_docker
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/01-dump.sql:ro
      - ./docker/mysql/init-extratables.sql:/docker-entrypoint-initdb.d/01-extras.sql:ro
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - internal

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8011:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.202.0/28
